@echo-off
echo > abiru.html
echo > aburame-muta.html
echo > aburame-shibi.html
echo > aburame-shikuro.html
echo > aburame-shino.html
echo > aburame-tatsuma.html
echo > aburame-torune.html
echo > ajisai.html
echo > akatsuchi.html
echo > akimichi-chobee.html
echo > akimichi-chocho.html
echo > akimichi-choji's-mum.html
echo > akimichi-choji.html
echo > akimichi-choza.html
echo > akimichi-doto.html
echo > akimichi-karui.html
echo > akimichi-makaro.html
echo > akimichi-maruten.html
echo > akimichi-shito.html
echo > akimichi-torifu.html
echo > amai.html
echo > ameno.html
echo > ameyuri-ringo.html
echo > ami.html
echo > anko-mitarashi.html
echo > ao.html
echo > aoba-yamashiro.html
echo > arashi.html
echo > araya.html
echo > atsui.html
echo > ayame.html
echo > azami.html
echo > baiu.html
echo > baki.html
echo > beekeeper.html
echo > bekko.html
echo > benga.html
echo > blue-b.html
echo > bunpuku.html
echo > burami.html
echo > byakuren.html
echo > c.html
echo > chen.html
echo > chinoike-chino.html
echo > chinoike-en-oyashiro.html
echo > chiriku.html
echo > chiyo.html
echo > chojuro.html
echo > chukaku.html
echo > chukichi.html
echo > daibutsu.html
echo > daikoku-funeno.html
echo > daimaru.html
echo > dan-kato.html
echo > darui.html
echo > datsuji.html
echo > deidara.html
echo > dodai.html
echo > doshu-goetsu.html
echo > dosu-kinuta.html
echo > ebisu.html
echo > ebizo.html
echo > enko-onikuma.html
echo > f.html
echo > first-raikage.html
echo > fourth-raikage.html
echo > fu.html
echo > fudo.html
echo > fuen.html
echo > fugi.html
echo > fuguki-suikazan.html
echo > fukai.html
echo > fuki.html
echo > furofuki.html
echo > furui.html
echo > fuuka.html
echo > fuyo.html
echo > gaara.html
echo > ganryu.html
echo > gari.html
echo > genma-shiranui.html
echo > gennai.html
echo > ginkaku.html
echo > goji.html
echo > gozu(sound).html
echo > gozu(kiri).html
echo > guren.html
echo > hachiya-tsurushi.html
echo > haie.html
echo > hakkaku.html
echo > haku's-parents.html
echo > yuki-haku.html
echo > hamaki-mimura.html
echo > han.html
echo > hanzaki.html
echo > hanzo.html
echo > haruno-kizashi.html
echo > haruno-mebuki.html
echo > harusame.html
echo > hassaku-onomichi.html
echo > hatake-kakashi.html
echo > hatake-sakumo.html
echo > hayama-shirakumo.html
echo > hayase.html
echo > hayate-gekko.html
echo > hebiichigo.html
echo > heiji.html
echo > hidan.html
echo > hikaru.html
echo > himatsu.html
echo > hinata-and-hanabi's-mum.html
echo > hinoko.html
echo > hisame.html
echo > hisen.html
echo > hoichi.html
echo > hoki-taketori.html
echo > hoki.html
echo > homura-mitokado.html
echo > hosei.html
echo > hoshigaki-kisame.html
echo > hoshigaki-shizuma.html
echo > hosho.html
echo > hozuki-gengetsu.html
echo > hozuki-mangetsu.html
echo > hozuki-suigetsu.html
echo > human-path.html
echo > hyogo.html
echo > hyou.html
echo > hyuga-elder.html
echo > hyuga-hanabi.html
echo > hyuga-hiashi.html
echo > hyuga-hizashi.html
echo > hyuga-hoheto.html
echo > hyuga-iroha.html
echo > hyuga-ko.html
echo > hyuga-natsu.html
echo > hyuga-neji.html
echo > hyuga-tetsu.html
echo > hyuga-tokuma.html
echo > ichirota-oniyuzu.html
echo > inoha.html
echo > inomatsu.html
echo > inuzuka-akita.html
echo > inuzuka-gaku.html
echo > inuzuka-hana.html
echo > inuzuka-kiba.html
echo > inuzuka-tsume.html
echo > ishikawa.html
echo > ittan.html
echo > iwabe-yuino.html
echo > iwana-akame.html
echo > iwashi-tatami.html
echo > iyashi.html
echo > izumo-kamizuki.html
echo > j.html
echo > jigumo.html
echo > jinin-akebino.html
echo > jinpachi-munashi.html
echo > jiraiya.html
echo > jirobo.html
echo > jugo.html
echo > junsai.html
echo > juzo-biwa.html
echo > k.html
echo > kagari.html
echo > kagero.html
echo > kakko.html
echo > kako.html
echo > kakui.html
echo > kakuzu.html
echo > kamikiri.html
echo > kaminarimon-denki.html
echo > kaminarimon-ereki.html
echo > kamizuru-jibachi.html
echo > kamizuru-kurobachi.html
echo > kamizuru-suzumebachi.html
echo > kandachi.html
echo > kankuro.html
echo > kanpo.html
echo > karai.html
echo > karatachi-kagura.html
echo > karatachi-yagura.html
echo > karura.html
echo > karyu.html
echo > kashike.html
echo > kasumi.html
echo > katasuke-tono.html
echo > kayui.html
echo > kazami.html
echo > kazan.html
echo > kazuma.html
echo > kegon.html
echo > kidomaru.html
echo > kigiri.html
echo > kiho.html
echo > killer-b.html
echo > kimimaro.html
echo > kin-tsuchi.html
echo > kinkaku.html
echo > kirara.html
echo > kirisame.html
echo > kitane.html
echo > kito.html
echo > kitsuchi.html
echo > kiyoi-yotsuki.html
echo > kohaku-ichizoku.html
echo > koharu-utatane.html
echo > koji.html
echo > kokuyo.html
echo > komaza.html
echo > komugi.html
echo > komushi.html
echo > konan.html
echo > korobi.html
echo > kosuke-maruboshi.html
echo > kosuke.html
echo > kotetsu-hagane.html
echo > kotohime.html
echo > kozuchi.html
echo > ku.html
echo > kumade-toriichi.html
echo > kumadori.html
echo > kunugi-mokume.html
echo > kurama-murakumo.html
echo > kurama-unkai.html
echo > kurama-uroko.html
echo > kurama-yakumo.html
echo > kuroi-hako.html
echo > kurosuki-buntan.html
echo > kurosuki-raiga.html
echo > kurotsuchi.html
echo > kushimaru-kuriarare.html
echo > kussaku.html
echo > kusushi.html
echo > kyoho-fuefuki.html
echo > kyusuke.html
echo > lee-metal.html
echo > lee-rock.html
echo > log.html
echo > mabui.html
echo > mahiru.html
echo > maki.html
echo > mamushi.html
echo > marui.html
echo > matsuri.html
echo > mawashi-dokuraku.html
echo > mei-terumi.html
echo > meizu.html
echo > midare.html
echo > midori.html
echo > might-dai.html
echo > might-guy.html
echo > mijin.html
echo > mikoshi.html
echo > minato-namikaze.html
echo > minoji.html
echo > misumi-tsurugi.html
echo > misuno.html
echo > mitate.html
echo > mitsuki.html
echo > mizuki-touji.html
echo > moegi-kazamatsuri.html
echo > mogusa.html
echo > monga.html
echo > morino-ibiki.html
echo > morino-idate.html
echo > motoi.html
echo > mu.html
echo > mubi.html
echo > mugino.html
echo > mui.html
echo > mujin.html
echo > mujo.html
echo > muku.html
echo > murasame.html
echo > musai.html
echo > muyami.html
echo > namida-suzumeno.html
echo > nara-daen.html
echo > nara-enchu.html
echo > nara-ensui.html
echo > nara-kasuga.html
echo > nara-maen.html
echo > nara-shikadai.html
echo > nara-shikaku.html
echo > nara-shikamaru.html
echo > nara-suzaku.html
echo > nara-temari.html
echo > nara-yoshino.html
echo > natori.html
echo > natsu.html
echo > nauma.html
echo > nejiri.html
echo > nigai.html
echo > nonota.html
echo > nowaki.html
echo > nurari.html
echo > nurui.html
echo > oboro.html
echo > okei.html
echo > omoi.html
echo > onoki.html
echo > orochimaru.html
echo > osoi.html
echo > oyone.html
echo > pakura.html
echo > preta-path.html
echo > raido-namiashi.html
echo > ranka.html
echo > rasa.html
echo > renga-kokubo.html
echo > reto.html
echo > rin-nohara.html
echo > rinji.html
echo > ro.html
echo > roshi.html
echo > ruka.html
echo > ryusui.html
echo > ryuzetsu.html
echo > sagan.html
echo > sajin.html
echo > sakon-and-ukon.html
echo > samidare.html
echo > samui.html
echo > sana.html
echo > sari.html
echo > sarutobi-asuma.html
echo > sarutobi-biwako.html
echo > sarutobi-hiruzen.html
echo > sarutobi-konohamaru.html
echo > sarutobi-kurenai.html
echo > sarutobi-mirai.html
echo > sarutobi-sasuke.html
echo > sasame.html
echo > sasori-parents.html
echo > sasori.html
echo > saya.html
echo > second-raikage.html
echo > seito.html
echo > sekiei's-partner.html
echo > sekiei.html
echo > sekieispectator.html
echo > sekki.html
echo > sen.html
echo > senju-butsuma.html
echo > senju-hashirama.html
echo > senju-itama.html
echo > senju-kawarama.html
echo > senju-mito.html
echo > senju-nawaki.html
echo > senju-tobirama.html
echo > senju-toka.html
echo > senju-tsunade.html
echo > shamon.html
echo > shiba.html
echo > shibire.html
echo > shibuki.html
echo > shigure.html
echo > shiho.html
echo > shimon-hijiri.html
echo > shimura-danzo.html
echo > shin-uchiha.html
echo > shin.html
echo > shinki.html
echo > shinko-inari.html
echo > shinku-yuhi.html
echo > shinobu-mibu.html
echo > shiore.html
echo > shira.html
echo > shishio.html
echo > shizuku.html
echo > shizune.html
echo > sora.html
echo > suien.html
echo > suiren(kiri).html
echo > suiren(rain).html
echo > suiu.html
echo > sumashi.html
echo > sumire-kakei.html
echo > suzume.html
echo > taiseki.html
echo > tajiki.html
echo > tango.html
echo > tanzo.html
echo > tarui.html
echo > tayuya.html
echo > team-goji-leader.html
echo > tekuno-kanden.html
echo > tenga.html
echo > tenma-izumo.html
echo > tenten.html
echo > tenuki-shigaraki.html
echo > tenzo.html
echo > teuchi.html
echo > tezuna.html
echo > third-kazekage.html
echo > third-mizukage.html
echo > third-raikage.html
echo > tobio.html
echo > tokara.html
echo > tomari.html
echo > tonbo-tobitake.html
echo > toroi(magnet-style).html
echo > toroi(chunin-exams).html
echo > tou.html
echo > tsuchino.html
echo > tsuru-itoi.html
echo > tsuzumi-sarugaku.html
echo > uchiha-baru.html
echo > uchiha-fugaku.html
echo > uchiha-hikaku.html
echo > uchiha-inabi.html
echo > uchiha-itachi.html
echo > uchiha-izumi.html
echo > uchiha-izuna.html
echo > uchiha-kagami.html
echo > uchiha-madara.html
echo > uchiha-mikoto.html
echo > uchiha-naka.html
echo > uchiha-naori.html
echo > uchiha-obito's-grandma.html
echo > uchiha-obito.html
echo > uchiha-rai.html
echo > uchiha-sakura.html
echo > uchiha-sarada.html
echo > uchiha-sasuke.html
echo > uchiha-setsuna.html
echo > uchiha-shisui.html
echo > uchiha-taiko.html
echo > uchiha-tajima.html
echo > uchiha-tekka.html
echo > uchiha-teyaki.html
echo > uchiha-uruchi.html
echo > uchiha-yakumi.html
echo > uchiha-yashiro.html
echo > udon-ise.html
echo > umino-ikkaku.html
echo > umino-iruka.html
echo > umino-kohari.html
echo > urushi.html
echo > utakata.html
echo > uzumaki-ashina.html
echo > uzumaki-boruto.html
echo > uzumaki-fuso.html
echo > uzumaki-himawari.html
echo > uzumaki-hinata.html
echo > uzumaki-karin's-mum.html
echo > uzumaki-karin.html
echo > uzumaki-kushina.html
echo > uzumaki-nagato.html
echo > uzumaki-naruto.html
echo > wasabi-izuno.html
echo > yahiko.html
echo > yajirobee.html
echo > yakushi-kabuto.html
echo > yakushi-nono.html
echo > yamanaka-fu.html
echo > yamanaka-ino's-mum.html
echo > yamanaka-ino.html
echo > yamanaka-inoichi.html
echo > yamanaka-inojin.html
echo > yamanaka-kohan.html
echo > yamanaka-sai.html
echo > yamanaka-santa.html
echo > yaoki.html
echo > yashamaru.html
echo > yodo.html
echo > yome.html
echo > yoro.html
echo > yoroi-akado.html
echo > yudachi.html
echo > yugao-uzuki.html
echo > yugito-nii.html
echo > yukai.html
echo > yukata.html
echo > yuki-minazuki.html
echo > yukimaru.html
echo > yura.html
echo > yurika.html
echo > yurito.html
echo > yurui(chunin-exams).html
echo > yurui(shinobi).html
echo > zabuza-momochi.html
echo > zaji.html
echo > zaku-abumi.html
echo > zosui.html
echo-Done-creating-files.
pause